name: Pre-Release Checks

on:
  pull_request:
    branches: [main]

jobs:
  pre-release-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Pre-Release Checks
        uses: whilesmart/workflows/js/pre-release@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
